Update Nile to work with Cairo 0.9.0
OpenZeppelin/nile pull request #131
Opened 2022-06-14 14:42 UTC by EvolveArt

Still WIP update of nile for cairo 0.9.0
- Registers class hash declarations in a `declarations.txt` file
- Add `max_fee` param to both `nre` and `cli` as per this [PR](https://github.com/OpenZeppelin/nile/pull/129)

Let me know what else should be added.

2022-06-16 18:47 UTC, trevis-dev commented
Nice initiative, @EvolveArt !

I hope the team will have some time to review these non-contracts PR soon. I don't think it's too good for Nile to be severely limited in it's unusability for weeks at this stage... and we like that tool.
So, in the meantime, I think I'll squeeze this in my own repo to continue  (any upcoming updates ?)

2022-06-20 17:21 UTC, andrew-fleming requested changes
@EvolveArt this is looking really good! Thank you for starting this! I left some comments and questions. We should also update the current tests, add new test cases for `declare`, and update the README accordingly.

We'd like to have this ready for the upcoming Contracts v0.2.0 release. Do you think you can have this finished in the next few days? No pressure! If you're not available and/or it's too much too soon, we'd be happy to pick this up :) just let us know

2022-06-22 09:13 UTC, EvolveArt commented
Hello @andrew-fleming ! I was a bit in a rush with the release of my app yesterday, but I'll try my best to finish this ASAP :)

2022-06-22 09:20 UTC, EvolveArt commented on src/nile/core/account.py
> +    def send(self, to, method, calldata, nonce=None, max_fee=None):
Well true but `max_fee=0` is an invalid default parameter so imo might make more sense to have it as `None`

2022-06-22 09:21 UTC, EvolveArt commented on src/nile/core/declare.py
> +    address, tx_hash = parse_deployment(output)
it is for sure

2022-06-22 09:43 UTC, EvolveArt commented
Also, was wondering if we should include declaration in the `deploy` command or have something like `declare_and_deploy` ?

2022-06-22 21:37 UTC, andrew-fleming commented
> Hello @andrew-fleming ! I was a bit in a rush with the release of my app yesterday, but I'll try my best to finish this ASAP :)

No worries! I very much appreciate it 🙏 and congrats on your app's release!!

> Also, was wondering if we should include declaration in the `deploy` command or have something like `declare_and_deploy` ?

Haha I was thinking the same thing in the review a la `call_or_invoke`. I think putting them together could work...I cannot think of a better name, unfortunately. Maybe `declare_or_deploy` to not infer that both actions _will_ occur?

2022-06-23 11:22 UTC, EvolveArt commented
> Haha I was thinking the same thing in the review a la `call_or_invoke`. I think putting them together could work...I cannot think of a better name, unfortunately. Maybe `declare_or_deploy` to not infer that both actions _will_ occur?

Fair enough, will add that then 😄 

I got some issues when trying to run tests on my mac M1 but will try too fix that then we should be pretty much good with that PR. Let me know what's missing

2022-06-24 01:35 UTC, andrew-fleming reviewed
Very good improvements, sir! I left a few questions and comments. A few things to note:
- in `tox.ini`, we need to change the pinned `werkzeug` to `werkzeug==2.0.3` [here](https://github.com/EvolveArt/nile/blob/cairo0.9.0/tox.ini#L16); otherwise, there's a versioning conflict and I believe cairo-lang defaults back to v0.8.2 for tests
  - maybe we can remove the pinned `werkzeug` altogether because `starknet-devnet` already sets it to v2.0.3?
- correct me if I'm wrong, but I think we need to include a conditional to `account.send` that sets `max_fee` to `0` if it's `None` [here](https://github.com/EvolveArt/nile/blob/cairo0.9.0/src/nile/core/account.py#L58-L62) (to play nicely with our signer)
- in `cli.py`, shouldn't we include a click option for `--max_fee` and add it to `invoke` and `send`? Let me know if I'm mistaken

Testing:
- in `test_signer.py`, we need to replace `ContractDefinition` [here](https://github.com/EvolveArt/nile/blob/cairo0.9.0/tests/test_signer.py#L10) with `ContractClass` in building the Account instance
- I noticed our node tests are failing. My first guess is it has to do with `starknet-devnet` changing their default port to `5050`, but I'm not sure. Either way, we should rectify the tests
- and of course, test our new `declare`

Phew! Sorry for all the comments here^ and not where they're more in context :)

2022-06-24 01:41 UTC, andrew-fleming commented on src/nile/core/call_or_invoke.py
> +        command.append(str(max_fee))
```
    return subprocess.check_output(command).strip().decode("utf-8")
```
Whoops 😅 what the emoji was point to^

2022-06-24 14:14 UTC, martriay requested changes
Great PR, thanks for it! I added some comments in addition to Andrew's points

2022-06-24 14:14 UTC, martriay commented on src/nile/core/declare.py
> +    deployments.register_class_hash(class_hash, network, alias)
mh although the other scenario also applies: registering something and then not having it recorded onchain. maybe a smart deletion if the tx fails, but if it's too complex we can leave it out of scope for this PR

2022-06-24 14:51 UTC, EvolveArt commented on src/nile/core/account.py
> +            max_fee = 0
The signer defaults max_fee to 0 but yes anyway, not proving it or setting it to zero will yield the same result

2022-06-24 14:51 UTC, EvolveArt commented on src/nile/common.py
> +DECLARATIONS_FILENAME = "declarations.txt"
Definitely, all of this could probably be stored in one same `.json` file

2022-06-24 14:53 UTC, EvolveArt commented on src/nile/core/account.py
> +            calls=[[target_address, method, calldata]],
Hm you mean that we could not just sign a message ?

2022-06-24 16:55 UTC, EvolveArt commented on src/nile/core/declare.py
> +    deployments.register_class_hash(class_hash, network, alias)
You mean that if a class hash for this alias has already been register we don't send the tx right ?

2022-06-24 16:58 UTC, martriay commented on src/nile/core/declare.py
> +    deployments.register_class_hash(class_hash, network, alias)
right, because otherwise it will send the tx and then fail to register

2022-06-24 17:02 UTC, martriay commented on src/nile/core/account.py
> +            calls=[[target_address, method, calldata]],
sorry i mixed up. i think this is ok

2022-06-30 17:15 UTC, martriay commented
Superseded by #135

2022-06-30 17:15 UTC, closed without merging