Update to cairo-lang v0.9.0
OpenZeppelin/nile pull request #135
Opened 2022-06-30 03:11 UTC by andrew-fleming

Supercedes #131 and resolves #130.

This PR proposes to:
- add `max_fee` to the tx flow
- include `declare` command in CLI and NRE
  - tracks declarations in a `declarations.txt`
- update cairo-lang to v.0.9.0 in tox dependencies
- update signer to use `contract_class` instead of `contract_def`

---

Tests forthcoming.

2022-07-01 16:00 UTC, martriay requested changes
Looking good! Left a few comments

2022-07-01 18:36 UTC, andrew-fleming commented on src/nile/nre.py
> +    def get_declaration(self, identifier):
If I understand your question correctly, it's usable in the NRE. Users can declare a class in the script and just use the returned hash, but I'm thinking this adds flexibility if the class is already declared in their `declarations.txt`

2022-07-01 19:02 UTC, andrew-fleming commented on src/nile/core/call_or_invoke.py
> +    output = subprocess.check_output(command).strip().decode("utf-8")
Yes, the `max_fee` will always be included (set to `0` if not included by users). Even if we didn't set it automatically, there's latency between sending and rejecting a tx; thus, an exception won't be raised here

2022-07-05 17:38 UTC, andrew-fleming commented on src/nile/nre.py
> +    def get_declaration(self, identifier):
Good call

2022-07-05 17:46 UTC, martriay approved these changes
Very good! Left few comments, I also think we should document `get_declaration`.

Otherwise, good to go!

2022-07-05 17:46 UTC, martriay commented on README.md
> +Execute a transaction through the `Account` associated with the private key provided.  The syntax is:
```suggestion
Execute a transaction through the `Account` associated with the private key provided. The syntax is:
```

2022-07-05 17:46 UTC, martriay commented on src/nile/deployments.py
> +    if hash_exists(hash, network):
i liked the term _class_, although I see how the class could be represented by an alias. in any case "hash" is a bit generic in any crypto context 😅 

i vote for either `class_exists` or `class_hash_exists`, or similar

2022-07-05 17:46 UTC, martriay commented on src/nile/deployments.py
> +        raise Exception(f"Hash {hash[:6]}...{hash[-6:]} already exists in {file}")
i like this message better

2022-07-06 16:57 UTC, merged