Allow hex params in calldata for deployments through Account
OpenZeppelin/nile pull request #318
Opened 2022-11-29 22:15 UTC by ericnordelo

Fixes #317

2022-11-29 23:57 UTC, martriay approved these changes

2022-11-29 23:58 UTC, martriay requested changes
can you add tests for it? the ones that would have prevented us from releasing without this :)

2022-11-30 17:30 UTC, martriay approved these changes

2022-12-01 07:02 UTC, andrew-fleming approved these changes
Looks good to go!

2022-12-01 22:14 UTC, merged