Added support for signer
OpenZeppelin/nile pull request #33
Opened 2021-11-18 15:12 UTC by exp-table

2021-11-19 21:48 UTC, fracek commented on src/nile/commands/proxy.py
> +    else: #doesn't exist, havbe to deploy
There should be a space between `#` and `doesn't`. There's a type (`havbe` should be `have`).

2021-11-19 21:49 UTC, fracek commented on src/nile/commands/proxy.py
> +        #initialize account
Space between `#` and `initialize`

2021-11-19 21:50 UTC, fracek commented
I like this! I added a couple of nitpicky comments.

2021-11-19 21:52 UTC, exp-table commented
> I like this! I added a couple of nitpicky comments.

Fixed it!

2021-11-19 22:51 UTC, fracek commented
Ok there are a couple of linting issues. My advice is to run `tox -e format` to automatically format everything, then `tox -e lint` to double check everything is formatted correctly.

2021-11-20 06:30 UTC, martriay commented
This looks very nice! Do you think `proxy` could be merged into `send`? Or maybe I'm not understanding the different use case. In any case, I don't think that's the right name for it since it refers to a different kind of contracts which delegate execution to other contracts. Maybe `raw_execute`?

Future work could be:

1. auto generating a few accounts on `nile node`, have a default one and `--account` to select by index or alias
2. generating a private key, needed for `1` and pretty useful

2021-11-20 10:31 UTC, exp-table commented on src/nile/commands/proxy.py
> +        subprocess.run(f"nile deploy Account {signer.public_key} --alias account-{signer.index}", shell=True)
I didn't even think about it when prototyping initially. Good catch, fixed it!

2021-11-20 10:35 UTC, exp-table commented
> This looks very nice! A few comments:
> 
>     * Do you think `proxy` could be merged into `send`? Or maybe I'm not understanding the different use case. In any case, I don't think that's the right name for it since it refers to a different kind of contracts which delegate execution to other contracts. Maybe `raw_execute`?
> 
>     * Could you expand the documentation to include an example env file and commands snippets with actual parameters? That help users a lot.
> 

I renamed them to `send` and `raw-execute`. As you said, `proxy` isn't the right label for what it does.
I also added an example `example.env` file as well as enhanced documentations for `send` and `raw-execute`.

2021-11-20 20:04 UTC, fracek approved these changes
Looks good to me. All issues have been addressed, thanks!

2021-12-03 21:25 UTC, fracek commented on src/nile/signer.py
> +from starkware.cairo.common.hash_state import compute_hash_on_elements
This should be be wrapped in a try catch to avoid throwing when users don't have cairo installed yet (and want to use nile to install it).

2021-12-03 21:26 UTC, fracek commented
One last thing before I'm ready to merge. Sorry for letting you wait so long to review this PR!

2021-12-03 21:28 UTC, martriay requested changes

2021-12-03 21:28 UTC, martriay commented on README.md
> +1. `nile set <env_var>` looks for an environement variable with the same name whose value is a private key
there's no `nile set` command :)

2021-12-03 21:44 UTC, fracek commented on README.md
> +You can find an exemple `.env` file in `example.env`. These are private keys only to be used for testing and never in production.
`exemple` -> `example`

2021-12-04 14:50 UTC, fracek requested changes
Looks like it works well on a local network but does not work on mainnet because the network argument is missing in the call to get the nonce.

2021-12-04 14:50 UTC, fracek commented on src/nile/signer.py
> +            f"nile call account-{self.index} get_nonce", shell=True, encoding="utf-8"
Here it's missing a `--network` argument so when using a non-default network this call fails

2021-12-04 16:41 UTC, fracek approved these changes
I run this in a fresh venv and everything is working as expected

2021-12-05 02:27 UTC, martriay approved these changes

2021-12-05 02:28 UTC, merged

2021-12-05 02:28 UTC, martriay commented
Thanks all 🎉