Bump cairo lang dependency
OpenZeppelin/nile pull request #351
Opened 2023-04-12 10:15 UTC by ericnordelo

Fixes #350

2023-04-12 17:01 UTC, andrew-fleming submitted a review, later dismissed
Looks good to me!

2023-04-17 06:12 UTC, amayvs requested changes
@ericnordelo `starknet-devnet` released [v0.5.0](https://github.com/Shard-Labs/starknet-devnet/releases/tag/v0.5.0) 3 days ago.

Might be a worthwhile change before merge?

2023-04-17 06:12 UTC, amayvs commented on setup.cfg
> +    starknet-devnet>=0.5.0a2
```suggestion
    starknet-devnet>=0.5.0
```

2023-04-17 06:12 UTC, amayvs commented on tox.ini
> +    starknet-devnet==0.5.0a2
```suggestion
    starknet-devnet==0.5.0
```

2023-04-19 23:07 UTC, amayvs commented
@andrew-fleming @ericnordelo Anything I can do to assist in getting this merged and released?

2023-04-20 05:01 UTC, andrew-fleming approved these changes

2023-04-20 05:01 UTC, merged

2023-04-20 05:02 UTC, andrew-fleming commented
@amayvs sorry for the delay, the OZ team has an event going on all week. I'll release this as soon as I can